// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package user

type User struct {
	UserID   int32  `json:"user_id"`
	Username string `json:"username"`
	Password string `json:"password"`
	Email    string `json:"email"`
}
